In [17]:
import pandas as pd
import requests 
from tqdm import tqdm 
import numpy as np
import random
import time

In [12]:
def get_puuid(user):
    username_url = f'https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/{user}?api_key={riot_api_key}'
    userName = requests.get(username_url).json()
    userPuuid = userName['puuid']
    return userPuuid

In [11]:
def get_matchid(userPuuid,num):
    usermatch_url = f'https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/{userPuuid}/ids?type=ranked&start=0&count={num}&api_key={riot_api_key}'
    userMatch= requests.get(usermatch_url).json()
    return userMatch

In [10]:
def get_matches_timelines(userMatchid):
    usermatchdata_url = f'https://asia.api.riotgames.com/lol/match/v5/matches/{userMatchid}?api_key={riot_api_key}'
    matches = requests.get(usermatchdata_url).json()
    usertimeline_url = f'https://asia.api.riotgames.com/lol/match/v5/matches/{userMatchid}/timeline?api_key={riot_api_key}'
    timeline = requests.get(usertimeline_url).json()
    return matches, timeline


In [19]:
def get_rawdata(tier):
    division_list = ['I', 'II', 'III', 'IV']
    lst = []
    page = random.randrange(1, 5)
    print('get_SummonerName....from', page,'page')
    for division in tqdm(division_list):
        url = f'https://kr.api.riotgames.com/lol/league/v4/entries/RANKED_SOLO_5x5/{tier}/{division}?page={page}&api_key={riot_api_key}'
        res = requests.get(url).json()
        lst += random.sample(res, 5)
    summonerName_lst = list(map(lambda x: x['summonerName'], lst))

    print('get puuid.....')
    puuid_lst = []
    for i in tqdm(summonerName_lst):
        try:
            puuid_lst.append(get_puuid(i))
        except:
            print(i)
            continue

    print('get_match_id........')
    match_id_lst = []
    for j in tqdm(puuid_lst):
        match_id_lst += get_matchid(j, 3)

    print('get matches & timeline ......')
    df_create = []
    for match_id in tqdm(match_id_lst):
        matches, timeline = get_matches_timelines(match_id)
        time.sleep(2)
        df_create.append([match_id, matches, timeline])

    df = pd.DataFrame(df_create, columns=['match_id', 'matches', 'timeline'])
    print('complete')

    return df

In [15]:
riot_api_key = 'RGAPI-82547be3-cc5e-4af4-9d63-d240fadc606d'

In [24]:
df = get_rawdata('GOLD')

get_SummonerName....from 2 page


100%|██████████| 4/4 [00:03<00:00,  1.02it/s]


get puuid.....


100%|██████████| 20/20 [00:15<00:00,  1.26it/s]


get_match_id........


100%|██████████| 20/20 [00:15<00:00,  1.25it/s]


get matches & timeline ......


100%|██████████| 60/60 [04:08<00:00,  4.14s/it]

complete


In [25]:
df

match_id                                            matches  \
0   KR_6447470029  {'metadata': {'dataVersion': '2', 'matchId': '...   
1   KR_6445128745  {'metadata': {'dataVersion': '2', 'matchId': '...   
2   KR_6445097524  {'metadata': {'dataVersion': '2', 'matchId': '...   
3   KR_6455294133  {'metadata': {'dataVersion': '2', 'matchId': '...   
4   KR_6455227368  {'metadata': {'dataVersion': '2', 'matchId': '...   
5   KR_6454533844  {'metadata': {'dataVersion': '2', 'matchId': '...   
6   KR_6451869528  {'metadata': {'dataVersion': '2', 'matchId': '...   
7   KR_6451821377  {'metadata': {'dataVersion': '2', 'matchId': '...   
8   KR_6451787169  {'metadata': {'dataVersion': '2', 'matchId': '...   
9   KR_6448105512  {'metadata': {'dataVersion': '2', 'matchId': '...   
10  KR_6442808059  {'metadata': {'dataVersion': '2', 'matchId': '...   
11  KR_6324853964  {'metadata': {'dataVersion': '2', 'matchId': '...   
12  KR_6449227171  {'metadata': {'dataVersion': '2', 'matchId': '...   
13  KR_6449147646  {'metadata': {'dataVersion': '2', 'matchId': '...   
14  KR_6449095117  {'metadata': {'dataVersion': '2', 'matchId': '...   
15  KR_6422028899  {'metadata': {'dataVersion': '2', 'matchId': '...   
16  KR_6422002360  {'metadata': {'dataVersion': '2', 'matchId': '...   
17  KR_6421967562  {'metadata': {'dataVersion': '2', 'matchId': '...   
18  KR_6442695941  {'metadata': {'dataVersion': '2', 'matchId': '...   
19  KR_6442640511  {'metadata': {'dataVersion': '2', 'matchId': '...   
20  KR_6418944408  {'metadata': {'dataVersion': '2', 'matchId': '...   
21  KR_6390213833  {'metadata': {'dataVersion': '2', 'matchId': '...   
22  KR_6390199030  {'metadata': {'dataVersion': '2', 'matchId': '...   
23  KR_6390146215  {'metadata': {'dataVersion': '2', 'matchId': '...   
24  KR_6416778931  {'metadata': {'dataVersion': '2', 'matchId': '...   
25  KR_6383764094  {'metadata': {'dataVersion': '2', 'matchId': '...   
26  KR_6322715945  {'metadata': {'dataVersion': '2', 'matchId': '...   
27  KR_6454854960  {'metadata': {'dataVersion': '2', 'matchId': '...   
28  KR_6449893831  {'metadata': {'dataVersion': '2', 'matchId': '...   
29  KR_6449865479  {'metadata': {'dataVersion': '2', 'matchId': '...   
30  KR_6440193118  {'metadata': {'dataVersion': '2', 'matchId': '...   
31  KR_6438798516  {'metadata': {'dataVersion': '2', 'matchId': '...   
32  KR_6437881451  {'metadata': {'dataVersion': '2', 'matchId': '...   
33  KR_6454170399  {'metadata': {'dataVersion': '2', 'matchId': '...   
34  KR_6454106557  {'metadata': {'dataVersion': '2', 'matchId': '...   
35  KR_6454010982  {'metadata': {'dataVersion': '2', 'matchId': '...   
36  KR_6424921010  {'metadata': {'dataVersion': '2', 'matchId': '...   
37  KR_6421710843  {'metadata': {'dataVersion': '2', 'matchId': '...   
38  KR_6399091260  {'metadata': {'dataVersion': '2', 'matchId': '...   
39  KR_6407764638  {'metadata': {'dataVersion': '2', 'matchId': '...   
40  KR_6407716526  {'metadata': {'dataVersion': '2', 'matchId': '...   
41  KR_6329000899  {'metadata': {'dataVersion': '2', 'matchId': '...   
42  KR_6455137599  {'metadata': {'dataVersion': '2', 'matchId': '...   
43  KR_6454851797  {'metadata': {'dataVersion': '2', 'matchId': '...   
44  KR_6454814712  {'metadata': {'dataVersion': '2', 'matchId': '...   
45  KR_6452808744  {'metadata': {'dataVersion': '2', 'matchId': '...   
46  KR_6445791096  {'metadata': {'dataVersion': '2', 'matchId': '...   
47  KR_6444645727  {'metadata': {'dataVersion': '2', 'matchId': '...   
48  KR_6433767338  {'metadata': {'dataVersion': '2', 'matchId': '...   
49  KR_6416421395  {'metadata': {'dataVersion': '2', 'matchId': '...   
50  KR_6416347663  {'metadata': {'dataVersion': '2', 'matchId': '...   
51  KR_6446719666  {'metadata': {'dataVersion': '2', 'matchId': '...   
52  KR_6421998207  {'metadata': {'dataVersion': '2', 'matchId': '...   
53  KR_6400662359  {'metadata': {'dataVersion': '2', 'matchId': '...   
54  KR_6455106347  {'metadata': {'dataVersion': '

In [58]:
def get_match_timeline_df(df):
    df_creater = []
    df1 = []
    print('소환사 스텟 생성중...')
    for i in tqdm(range(len(df))):
        if df.iloc[0].matches['info']['gameDuration'] > 900:
            # matches 관련된 데이터
            for j in range(10):
                try:
                    tmp = []
                    tmp.append(df.iloc[i].match_id)
                    tmp.append(df.iloc[i].matches['info']['gameDuration'])
                    tmp.append(df.iloc[i].matches['info']['gameVersion'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['summonerName'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['summonerLevel'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['participantId'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['championName'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['champExperience'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['teamPosition'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['teamId'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['win'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['kills'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['deaths'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['assists'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['totalDamageDealtToChampions'])
                    tmp.append(df.iloc[i].matches['info']['participants'][j]['totalDamageTaken'])
                    for k in range(5, 26):
                        try:
                            tmp.append(df.iloc[i].timeline['info']['frames'][k]['participantFrames'][str(j + 1)]['totalGold'])
                        except:
                            tmp.append(0)
                    df_creater.append(tmp)
                except:
                    print(i)
                    continue

    columns = ['gameId', 'gameDuration', 'gameVersion', 'summonerName', 'summonerLevel', 'participantId',
               'championName', 'champExperience', 'teamPosition', 'teamId', 'win', 'kills', 'deaths', 'assists',
               'totalDamageDealtToChampions', 'totalDamageTaken', 'g_5', 'g_6', 'g_7', 'g_8', 'g_9', 'g_10', 'g_11',
               'g_12', 'g_13', 'g_14', 'g_15',
               'g_16', 'g_17', 'g_18', 'g_19', 'g_20', 'g_21', 'g_22', 'g_23', 'g_24', 'g_25']

    df1 = pd.DataFrame(df_creater, columns=columns).drop_duplicates()
    print('complete')
    return df1

In [54]:
df.iloc[0].timeline['info']['frames'][3]['participantFrames'][str(1)]['totalGold']

815

In [119]:
df1 = get_match_timeline_df(df)

소환사 스텟 생성중...


100%|██████████| 60/60 [00:00<00:00, 64.49it/s]


complete


In [100]:
df1.keys()

Index(['gameId', 'gameDuration', 'gameVersion', 'summonerName',
       'summonerLevel', 'participantId', 'championName', 'champExperience',
       'teamPosition', 'teamId', 'win', 'kills', 'deaths', 'assists',
       'totalDamageDealtToChampions', 'totalDamageTaken', 'g_5', 'g_6', 'g_7',
       'g_8', 'g_9', 'g_10', 'g_11', 'g_12', 'g_13', 'g_14', 'g_15', 'g_16',
       'g_17', 'g_18', 'g_19', 'g_20', 'g_21', 'g_22', 'g_23', 'g_24', 'g_25'],
      dtype='object')

In [101]:
len(df1)

600

In [123]:
for i in range(len(df1)):
  print(df1.iloc[i]['win'])
  df1['win'][i] = df1.iloc[i]['win']*1
  print('입력후',df1['win'][i],'입력할 값',df1.iloc[i]['win']*1)

True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
True
입력후 1 입력할 값 1
True
입

<ipython-input-123-99da77ce86f2>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['win'][i] = df1.iloc[i]['win']*1


입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
True
입력후 1 입력할 값 1
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할 값 0
False
입력후 0 입력할

In [125]:
df1['win'][8]

0

In [127]:
df1['win'].unique()

array([1, 0], dtype=object)

In [155]:
df1_input = df1[['g_15']]
df1_input.head()

g_15
0  5529
1  5297
2  6218
3  5795
4  4971

In [156]:
df1_input = df1_input.to_numpy()

In [157]:
df1_input[:20]

array([[5529],
       [5297],
       [6218],
       [5795],
       [4971],
       [4993],
       [7087],
       [5641],
       [6959],
       [5184],
       [5230],
       [6091],
       [5203],
       [4194],
       [2747],
       [4714],
       [5229],
       [5800],
       [5637],
       [3415]])

In [158]:
df1_target = df1.win.to_numpy()
df1_target[:10]

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=object)

In [132]:
len(df1)

600

In [133]:
from sklearn.model_selection import train_test_split

In [159]:
train_input, test_input, train_target, test_target= train_test_split(df1_input, df1_target, test_size =0.2 , random_state = 42)

In [160]:
train_input.shape

(480, 1)

In [ ]:
train_input

In [162]:
test_input.shape

(120, 1)

In [138]:
from sklearn.preprocessing import StandardScaler

In [163]:
ss = StandardScaler() #표준점수 정규화
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [164]:
train_input[:10]

array([[4575],
       [5184],
       [5895],
       [4740],
       [4492],
       [4654],
       [5891],
       [5740],
       [6032],
       [4864]])

In [165]:
train_scaled[:10]

array([[-0.573023  ],
       [-0.10547239],
       [ 0.44038719],
       [-0.44634673],
       [-0.63674501],
       [-0.51237194],
       [ 0.43731625],
       [ 0.32138826],
       [ 0.54556688],
       [-0.35114759]])

In [143]:
from sklearn.neighbors import KNeighborsClassifier

In [166]:
kn = KNeighborsClassifier(n_neighbors = 3)

In [ ]:
train_scaled

In [154]:
train_target

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [173]:
kn.fit(train_scaled, train_target)

KNeighborsClassifier(n_neighbors=3)

In [176]:
 test_target = test_target.astype(np.int)

<ipython-input-176-06d5e326a256>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_target = test_target.astype(np.int)


In [174]:
kn.score(train_input, train_target)

0.5

In [177]:
kn.score(test_input, test_target)

0.5

In [178]:
kn.score(test_scaled, test_target)

0.5583333333333333

In [179]:
import matplotlib.pyplot as plt

In [180]:
win_defeat_indexes = (train_target == 1) | (train_target == 0) #true of false로 해당 값 가져오기 
win_defeat_indexes

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [185]:
train_winrate = train_scaled[win_defeat_indexes]
target_winrate = train_target[win_defeat_indexes]

In [186]:
target_winrate

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [183]:
from sklearn.linear_model import LogisticRegression

In [187]:
lr = LogisticRegression()
lr.fit(train_winrate, target_winrate)

LogisticRegression()

In [188]:
lr.classes_

array([0, 1])

In [189]:
from scipy.special import expit 

In [191]:
decisions = lr.decision_function(train_winrate[:10])

In [192]:
decisions

array([-0.22438627, -0.04199093,  0.17095338, -0.17496881, -0.24924474,
       -0.20072579,  0.16975538,  0.12453092,  0.21198484, -0.13783084])

In [193]:
expit(decisions) 

array([0.44413762, 0.48950381, 0.54263456, 0.45636905, 0.4380094 ,
       0.44998636, 0.54233723, 0.53109256, 0.55279864, 0.46559674])

In [206]:
lr = LogisticRegression(C=1000,max_iter=100)

In [207]:
lr.fit(train_scaled, train_target)

LogisticRegression(C=1000)

In [209]:
lr = LogisticRegression(C=2,max_iter=1000)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

(0.5916666666666667, 0.6583333333333333)

In [210]:
lr = LogisticRegression(C=20,max_iter=10)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

(0.5916666666666667, 0.6583333333333333)

In [211]:
lr = LogisticRegression(C=2,max_iter=100)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

(0.5916666666666667, 0.6583333333333333)