In [1]:
import pandas as pd 
import numpy as np 

In [2]:
#데이터 전처리 
#KNN모델 사용  확률계산
#확률 확인

In [3]:
fish = pd.read_csv('https://bit.ly/fish_csv_data')

In [4]:
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [5]:
pd.unique(fish.Species) #컬럼의 값이 몇 종류 있는지 확인 가능 

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']]
fish_input.head()

Weight  Length  Diagonal   Height   Width
0   242.0    25.4      30.0  11.5200  4.0200
1   290.0    26.3      31.2  12.4800  4.3056
2   340.0    26.5      31.1  12.3778  4.6961
3   363.0    29.0      33.5  12.7300  4.4555
4   430.0    29.0      34.0  12.4440  5.1340

In [7]:
fish_input = fish_input.to_numpy()

In [8]:
fish_input[:5]

array([[242.    ,  25.4   ,  30.    ,  11.52  ,   4.02  ],
       [290.    ,  26.3   ,  31.2   ,  12.48  ,   4.3056],
       [340.    ,  26.5   ,  31.1   ,  12.3778,   4.6961],
       [363.    ,  29.    ,  33.5   ,  12.73  ,   4.4555],
       [430.    ,  29.    ,  34.    ,  12.444 ,   5.134 ]])

In [9]:
fish_target = fish.Species.to_numpy()
fish_target[:5]

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream'], dtype=object)

In [10]:
len(fish)

159

In [11]:
#데이터 나누기
from sklearn.model_selection import train_test_split

In [12]:
train_input, test_input, train_target, test_target= train_test_split(fish_input, fish_target, test_size =0.2 , random_state = 42)
#train input 80%값 
#test input 80% 값
#train_target 80%의 결과
#test_target 20%의 결과 
#test size 데이터 값중 0.2 = 20%만 사용 함

In [13]:
train_input.shape

(127, 5)

In [14]:
test_input.shape #두개의 합 159 = len(fish)
#5는 특성, 차원 수 

(32, 5)

In [15]:
#표준 점수 정규화
from sklearn.preprocessing import StandardScaler

In [16]:
ss = StandardScaler() #표준점수 정규화
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [17]:
train_input[:5]
#데이터 차이가 큰 폭은 모델이 방향을 못잡음(성능저하)

array([[ 51.5   ,  16.2   ,  17.2   ,   4.5924,   2.6316],
       [567.    ,  46.    ,  48.7   ,   7.792 ,   4.87  ],
       [340.    ,  26.5   ,  31.1   ,  12.3778,   4.6961],
       [120.    ,  22.    ,  23.5   ,   6.11  ,   3.4075],
       [160.    ,  22.5   ,  25.3   ,   7.0334,   3.8203]])

In [18]:
train_scaled[:5]
#표준점수를 반영해서 정규과정을 거침

array([[-0.95631423, -1.14878727, -1.22092909, -1.06273398, -1.10441696],
       [ 0.51397533,  1.65907911,  1.53608537, -0.25944123,  0.27042307],
       [-0.13346547, -0.17828312, -0.00434176,  0.89187139,  0.16361254],
       [-0.76094112, -0.60228979, -0.6695262 , -0.68172477, -0.62785406],
       [-0.64685464, -0.55517794, -0.51198251, -0.44989563, -0.37430959]])

In [19]:
#모델 선언 KNN
from sklearn.neighbors import KNeighborsClassifier

In [67]:
train_target

array(['Perch', 'Pike', 'Bream', 'Perch', 'Roach', 'Roach', 'Parkki',
       'Perch', 'Bream', 'Pike', 'Smelt', 'Perch', 'Parkki', 'Roach',
       'Perch', 'Bream', 'Perch', 'Perch', 'Perch', 'Bream', 'Perch',
       'Parkki', 'Perch', 'Bream', 'Smelt', 'Perch', 'Roach', 'Bream',
       'Pike', 'Bream', 'Pike', 'Perch', 'Parkki', 'Bream', 'Perch',
       'Pike', 'Bream', 'Perch', 'Parkki', 'Roach', 'Perch', 'Bream',
       'Roach', 'Perch', 'Bream', 'Bream', 'Perch', 'Perch', 'Roach',
       'Pike', 'Perch', 'Smelt', 'Pike', 'Roach', 'Perch', 'Parkki',
       'Perch', 'Bream', 'Perch', 'Smelt', 'Perch', 'Parkki', 'Smelt',
       'Perch', 'Perch', 'Roach', 'Bream', 'Perch', 'Perch', 'Roach',
       'Roach', 'Perch', 'Perch', 'Bream', 'Roach', 'Bream', 'Roach',
       'Parkki', 'Perch', 'Perch', 'Perch', 'Perch', 'Pike', 'Pike',
       'Perch', 'Bream', 'Perch', 'Bream', 'Whitefish', 'Pike', 'Bream',
       'Bream', 'Roach', 'Perch', 'Pike', 'Bream', 'Pike', 'Parkki',
       'Roach', 'Pe

In [20]:
kn = KNeighborsClassifier(n_neighbors = 3)
kn.fit(train_scaled, train_target)


KNeighborsClassifier(n_neighbors=3)

In [21]:
kn.score(train_input, train_target)

0.11023622047244094

In [22]:
kn.score(test_input, test_target)

0.09375

In [23]:
kn.score(train_scaled, train_target)

0.8976377952755905

In [24]:
kn.score(test_scaled, test_target)

0.875

In [25]:
import matplotlib.pyplot as plt

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
bream_smelt_indexes = (train_target =='Bream') | (train_target == 'Smelt') #true of false로 해당 값 가져오기 
bream_smelt_indexes

array([False, False,  True, False, False, False, False, False,  True,
       False,  True, False, False, False, False,  True, False, False,
       False,  True, False, False, False,  True,  True, False, False,
        True, False,  True, False, False, False,  True, False, False,
        True, False, False, False, False,  True, False, False,  True,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False,  True, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
        True,  True, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False,  True, False,  True,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False,  True,  True, False, False,  True, False,
       False])

In [28]:
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]

In [29]:
target_bream_smelt

array(['Bream', 'Bream', 'Smelt', 'Bream', 'Bream', 'Bream', 'Smelt',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Smelt', 'Bream', 'Smelt', 'Smelt', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream',
       'Smelt', 'Smelt', 'Bream', 'Smelt', 'Bream', 'Bream'], dtype=object)

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

LogisticRegression()

In [32]:
lr.classes_

array(['Bream', 'Smelt'], dtype=object)

In [33]:
from scipy.special import expit 
#시그노이드 함수

In [34]:
decisions = lr.decision_function(train_bream_smelt[:5])
#로지스틱스는 음수도 가지게 됨 

In [35]:
decisions #중간값, 실제있는 값들로 시그모이드 넣을 것 

array([-3.0865607 , -6.19033852,  3.57239355, -5.41198432, -4.37504209])

In [36]:
expit(decisions) 
#시그모이드 특징 0에서 1의 값만 가진다. 
#비선형 결과 값 

array([0.04366503, 0.00204494, 0.97267887, 0.00444295, 0.01243113])

In [37]:
#다중 분류 문제 해결
#파라미터값 C(정규화정도(데이터 특성에 따라 범위지정해서 정규화 진행), 하이퍼파라미터), max_iter
lr = LogisticRegression(C=20,max_iter=1000)

In [38]:
lr.fit(train_scaled, train_target)

LogisticRegression(C=20, max_iter=1000)

In [39]:
lr.score(train_scaled, train_target)

0.9291338582677166

In [40]:
lr.score(test_scaled, test_target)

0.90625

In [41]:
lr = LogisticRegression(C=2,max_iter=1000)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

(0.8188976377952756, 0.875)

In [42]:
lr = LogisticRegression(C=50,max_iter=1000)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

(0.9763779527559056, 0.90625)

In [43]:
lr = LogisticRegression(C=20,max_iter=10)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(0.8740157480314961, 0.90625)

In [44]:
lr = LogisticRegression(C=2,max_iter=100)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target), lr.score(test_scaled, test_target)

(0.8188976377952756, 0.875)

In [45]:
dec = lr.decision_function(test_scaled[:5])

In [46]:
dec

array([[-3.03206156,  0.78562747,  3.07892383, -1.96720113,  2.27794072,
         0.25956595, -1.40279528],
       [-5.35407116,  1.62709467,  2.73262059, -2.2862566 ,  1.9264793 ,
         4.64289686, -3.28876365],
       [-1.92596082, -2.32840196,  1.9921664 ,  3.47496971,  1.91752478,
        -1.92499471, -1.20530339],
       [-0.03980313,  0.19712691,  2.40939679, -0.59134667,  1.90724463,
        -3.82766786, -0.05495066],
       [-2.88482971, -0.66955396,  3.45569076, -0.3780332 ,  2.34370973,
        -0.9575771 , -0.90940651]])

In [47]:
#소수점 제거
dec = np.round(dec,2)
dec

array([[-3.03,  0.79,  3.08, -1.97,  2.28,  0.26, -1.4 ],
       [-5.35,  1.63,  2.73, -2.29,  1.93,  4.64, -3.29],
       [-1.93, -2.33,  1.99,  3.47,  1.92, -1.92, -1.21],
       [-0.04,  0.2 ,  2.41, -0.59,  1.91, -3.83, -0.05],
       [-2.88, -0.67,  3.46, -0.38,  2.34, -0.96, -0.91]])

In [48]:
#소프트맥스: 모든 값의 총합을 1이 되게 출력
from scipy.special import softmax

In [49]:
proba = softmax(dec, axis=1)

In [50]:
proba = np.round(proba,2)

In [51]:
proba[0]

array([0.  , 0.06, 0.61, 0.  , 0.28, 0.04, 0.01])

In [52]:
sum(proba[0])

1.0

In [53]:
sum(proba[1])

1.0

In [54]:
proba[0][0]

0.0

In [55]:
import os, sys
from google.colab import drive
import pandas as pd
import numpy as np
drive.mount('/content/drive')
lol_worlds_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset/League of Legends 2021 World Championship Play-In Groups Statistics - Raw Data.csv')

Mounted at /content/drive


In [56]:
lol_worlds_data.head()

Team    Player Opponent Position Champion  Kills  Deaths  Assists  \
0  UOL      Boss       GS      Top  Camille      4       5        3   
1   GS     Crazy      UOL      Top     Gwen      3       1        9   
2  UOL  Ahahacik       GS   Jungle  Trundle      2       4        5   
3   GS    Mojito      UOL   Jungle    Talon      5       4       10   
4  UOL    Nomanz       GS      Mid  Leblanc      1       3        4   

   Creep Score  Gold Earned  Champion Damage Share  Kill Participation  \
0          188        11107                   0.17                0.78   
1          217        12201                   0.20                0.52   
2          156         9048                   0.15                0.78   
3          194        11234                   0.23                0.65   
4          216         9245                   0.29                0.56   

   Wards Placed  Wards Destroyed  Ward Interactions  Dragons For  \
0             8                8                 16            0   
1            10                7                 17            4   
2             8               14                 22            0   
3            12                8                 20            4   
4             6                9                 15            0   

   Dragons Against  Barons For  Barons Against Result  
0                4           0               1      L  
1                0           1               0      W  
2                4           0               1      L  
3                0           1               0      W  
4                4           0               1      L

In [57]:
pd.unique(lol_worlds_data.Position)

array(['Top', 'Jungle', 'Mid', 'Adc', 'Support'], dtype=object)

In [58]:
adc_sup = (lol_worlds_data['Position']== 'Adc') | (lol_worlds_data['Position'] == 'Support')

In [59]:
adc_sup = lol_worlds_data[(lol_worlds_data['Position']== 'Adc') | (lol_worlds_data['Position'] == 'Support')]

In [60]:
adc_sup.head()

Team     Player Opponent Position      Champion  Kills  Deaths  Assists  \
6   UOL   Argonavt       GS      Adc        Ezreal      1       5        3   
7    GS      Alive      UOL      Adc  Miss Fortune      9       2        5   
8   UOL     Santas       GS  Support         Amumu      1       6        4   
9    GS  Zergsting      UOL  Support         Rakan      0       2       16   
16  DFM    Yutapon       C9      Adc          Jhin      1       0        1   

    Creep Score  Gold Earned  Champion Damage Share  Kill Participation  \
6           202         9539                   0.32                0.44   
7           273        15085                   0.27                0.61   
8            41         6328                   0.07                0.56   
9            42         7395                   0.05                0.70   
16          303        11579                   0.24                0.50   

    Wards Placed  Wards Destroyed  Ward Interactions  Dragons For  \
6              7                2                  9            0   
7             15                5                 20            4   
8             40               10                 50            0   
9             36                6                 42            4   
16             8                3                 11            0   

    Dragons Against  Barons For  Barons Against Result  
6                 4           0               1      L  
7                 0           1               0      W  
8                 4           0               1      L  
9                 0           1               0      W  
16                4           0               1      L

In [61]:
adc_sup['KPA'] = adc_sup['Kills']/(adc_sup['Assists']+1)

<ipython-input-61-26721319af5b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adc_sup['KPA'] = adc_sup['Kills']/(adc_sup['Assists']+1)


In [62]:
adc_sup['WPG'] = adc_sup['Wards Placed']/adc_sup['Gold Earned']

<ipython-input-62-27c73f1f3995>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  adc_sup['WPG'] = adc_sup['Wards Placed']/adc_sup['Gold Earned']


In [63]:
adc_sup

Team     Player Opponent Position      Champion  Kills  Deaths  Assists  \
6    UOL   Argonavt       GS      Adc        Ezreal      1       5        3   
7     GS      Alive      UOL      Adc  Miss Fortune      9       2        5   
8    UOL     Santas       GS  Support         Amumu      1       6        4   
9     GS  Zergsting      UOL  Support         Rakan      0       2       16   
16   DFM    Yutapon       C9      Adc          Jhin      1       0        1   
..   ...        ...      ...      ...           ...    ...     ...      ...   
209   C9     Vulcan      DFM  Support         Amumu      1       6        9   
216  UOL   Argonavt      BYG      Adc         Senna      1       3        9   
217  BYG      Doggo      UOL      Adc        Draven     10       2        4   
218  UOL     Santas      BYG  Support        Wukong      0       4        7   
219  BYG       Kino      UOL  Support         Rakan      0       5        9   

     Creep Score  Gold Earned  ...  Wards Placed  Wards Destroyed  \
6            202         9539  ...             7                2   
7            273        15085  ...            15                5   
8             41         6328  ...            40               10   
9             42         7395  ...            36                6   
16           303        11579  ...             8                3   
..           ...          ...  ...           ...              ...   
209           23         7594  ...            58                7   
216           58         9554  ...            35               16   
217          353        20546  ...            15                5   
218          200        10354  ...            16                8   
219           41         9304  ...            49               15   

     Ward Interactions  Dragons For  Dragons Against  Barons For  \
6                    9            0                4           0   
7                   20            4                0           1   
8                   50            0                4           0   
9                   42            4                0           1   
16                  11            0                4           0   
..                 ...          ...              ...         ...   
209                 65            4                2           0   
216                 51            1                4           1   
217                 20            4                1           1   
218                 24            1                4           1   
219                 64            4                1           1   

     Barons Against  Result   KPA       WPG  
6                 1       L  0.25  0.000734  
7                 0       W  1.50  0.000994  
8                 1       L  0.20  0.006321  
9                 0       W  0.00  0.004868  
16                1       L  0.50  0.000691  
..              ...     ...   ...       ...  
209               2       L  0.10  0.007638  
216               1       L  0.10  0.003663  
217               1       W  2.00  0.000730  
218               1       L  0.00  0.001545  
219               1       W  0.00  0.005267  

[88 rows x 22 columns]

In [64]:
train_data = adc_sup[['KPA','WPG','Champion Damage Share']].to_numpy()
target_data = adc_sup['Position'].to_numpy() #[] 시리즈 타입(1차원) [[]]데이터 프레임 타입(2차원)

In [65]:
train_data[:5]

array([[2.50000000e-01, 7.33829542e-04, 3.20000000e-01],
       [1.50000000e+00, 9.94365264e-04, 2.70000000e-01],
       [2.00000000e-01, 6.32111252e-03, 7.00000000e-02],
       [0.00000000e+00, 4.86815416e-03, 5.00000000e-02],
       [5.00000000e-01, 6.90905950e-04, 2.40000000e-01]])

In [66]:
target_data[:5]

array(['Adc', 'Adc', 'Support', 'Support', 'Adc'], dtype=object)